spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blood_email_db?createDatabaseIfNotExist=true
    username: root
    password: pandU@420
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
